var level1_0 = [
    { type: "reference", title: "Introduction level: Learning the ropes", ref: "level1_0" },
    { type:"worldInit", worldWidth: 1800, worldHeight: 960 },
    { type:"playerInit", posX: 200, posY: 860, velX: 4, velY: 0 },
    { ref: "background01", type: "overlayImage", url: "media/elements/background01_tile.png", posX: -300, posY: 400, width: 1408, height: 440 },
    { ref: "background01", type: "overlayImage", url: "media/elements/background01_tile.png", posX: 1108, posY: 400, width: 1408, height: 440 },
    { ref: "floortile", type: "overlayImage", url: "media/elements/floortile.png", posX: 0, posY: 40, width: 473, height: 120 },
    { ref: "floortile", type: "overlayImage", url: "media/elements/floortile.png", posX: 472, posY: 840, width: 473, height: 120 },
    { ref: "floortile", type: "overlayImage", url: "media/elements/floortile.png", posX: 944, posY: 840, width: 473, height: 120 },
    { ref: "floortile", type: "overlayImage", url: "media/elements/floortile.png", posX: 1336, posY: 840, width: 473, height: 120 },
    { ref: "fadedstalls01", type: "overlayImage", posX: 0, posY: 550, width: 1188, height: 232 },
    { ref: "fencetile", type: "overlayImage", url: "media/elements/fencetile.png", posX: 0, posY: 740, width: 462, height: 126 },
    { ref: "fencetile", type: "overlayImage", url: "media/elements/fencetile.png", posX: 462, posY: 740, width: 462, height: 126 },
    { ref: "fencetile", type: "overlayImage", url: "media/elements/fencetile.png", posX: 924, posY: 740, width: 462, height: 126 },
    { ref: "fencetile", type: "overlayImage", url: "media/elements/fencetile.png", posX: 1386, posY: 740, width: 462, height: 126 },
    { ref: "sign_pressandhold", type: "overlayImage", posX: 500, posY: 320 },
    { ref: "hypnotists_tent", type: "overlayImage", posX: 0, posY: 540 },
    { ref: "stain_barrel", type: "overlayImage", posX: 1010, posY: 870 },
    { ref: "fallingBarrel", name: "b1", type: "fallingBlock", classname: "fallingBarrel", posX: 1020, posY: 480, cellwidth: 118, cellheight: 571, numCells: 1, bbwidth: 118, bbheight: 571, bbOffsetX: 0, bbOffsetY: -100, seq: { wait: 1, hoist: 2, rest: 1, start: "resting" } },
    { ref: "impactSmoke_250x40", name: "smoke1", type: "triggeredAnim", trigger: "b1", posX: 960, posY: 843 },
    { name: "blocker1", type: "blocker", posX: 0 , posY: 160 , width: 40 , height: 800 },
    { name: "blocker2", type: "blocker", posX: 1480 , posY: 0 , width: 40 , height: 0 },
    { name: "blocker3", type: "blocker", posX: 70 , posY: 700 , width: 120 , height: 200 },
    { character: "velma", ref: "toffeeapple_pickup", name: "pickup1", type: "pickup", posX: 620, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "velma", ref: "toffeeapple_pickup", name: "pickup2", type: "pickup", posX: 720, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "velma", ref: "toffeeapple_pickup", name: "pickup3", type: "pickup", posX: 820, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "scooby", ref: "hotdog_pickup", name: "pickup1", type: "pickup", posX: 520, posY: 800, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "scooby", ref: "hotdog_pickup", name: "pickup2", type: "pickup", posX: 670, posY: 780, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "scooby", ref: "hotdog_pickup", name: "pickup3", type: "pickup", posX: 820, posY: 760, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "shaggy", ref: "burger_pickup", name: "pickup1", type: "pickup", posX: 1265, posY: 840, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "shaggy", ref: "burger_pickup", name: "pickup2", type: "pickup", posX: 1265, posY: 790, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "shaggy", ref: "burger_pickup", name: "pickup3", type: "pickup", posX: 1265, posY: 740, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "daphne", ref: "cottoncandy_pickup", name: "pickup1", type: "pickup", posX: 1150, posY: 740, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "daphne", ref: "cottoncandy_pickup", name: "pickup2", type: "pickup", posX: 1210, posY: 740, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "daphne", ref: "cottoncandy_pickup", name: "pickup3", type: "pickup", posX: 1270, posY: 740, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "fred", ref: "pop_pickup", name: "pickup1", type: "pickup", posX: 500, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "fred", ref: "pop_pickup", name: "pickup2", type: "pickup", posX: 790, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { character: "fred", ref: "pop_pickup", name: "pickup3", type: "pickup", posX: 1150, posY: 750, cellwidth: 60, cellheight: 60, numCells: 6,  bbwidth: 60, bbheight: 60, speed: 0.16 },
    { name: "line1", type: "line", edges: { type: "line", points: [0, worldHeight - 1, worldWidth + 1, worldHeight - 1] } },
    { name: "line2", type: "line", edges: { type: "onewayline", points: [0, 880, 1800, 880] } },
    { ref: "exit_clown", name: "exit1", type: "exitLevel", classname: "exit", posX: 1650, posY: 570, cellwidth: 163, cellheight: 294, numCells: 1, bbwidth: 100, bbheight: 100, bbOffsetX: 60, bbOffsetY: 50 }
];